/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package signin;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import static java.time.Instant.now;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import signin.Success;
import login.UserDB;

/**
 *
 * @author lailili
 */
public class SignIn extends javax.swing.JFrame {
    UserDB userDB;
    boolean info = false;
    int userid = 0;
    /**
     * Creates new form SignIn
     */
    public SignIn() {
        setVisible(true);
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        userDB = new UserDB();
        userDB.establishSQLConnection();
        initComponents();
        ImageIcon backgroundIcon = new ImageIcon("123.jpg");
        int width=Toolkit.getDefaultToolkit().getScreenSize().width;
        int height=Toolkit.getDefaultToolkit().getScreenSize().height;
        Image image = backgroundIcon.getImage().getScaledInstance(width, height, 1);
        backgroundIcon = new ImageIcon(image);
        backgroundLabel.setIcon(backgroundIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();
        signInlb = new javax.swing.JLabel();
        fillIn = new javax.swing.JLabel();
        firstNamelb = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        lastNamelb = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        info1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        signIn = new javax.swing.JButton();
        info2 = new javax.swing.JLabel();
        genderlb = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        info3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        month = new javax.swing.JComboBox<>();
        day = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        emailAddresslb = new javax.swing.JLabel();
        emailAddress = new javax.swing.JTextField();
        phoneNumberlb = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        info4 = new javax.swing.JLabel();
        info5 = new javax.swing.JLabel();
        phoneNumber = new javax.swing.JTextField();
        passwordlb = new javax.swing.JLabel();
        passWord = new javax.swing.JPasswordField();
        confirmlb = new javax.swing.JLabel();
        confirmPassword = new javax.swing.JPasswordField();
        confirmInfo = new javax.swing.JLabel();
        passwordinfo = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerPanel.setAlignmentX(0.0F);
        centerPanel.setAlignmentY(0.0F);
        centerPanel.setOpaque(false);
        centerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signInlb.setBackground(new java.awt.Color(255, 255, 255));
        signInlb.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        signInlb.setText("New User Sign In");
        centerPanel.add(signInlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 68, 518, -1));

        fillIn.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        fillIn.setText("Please fill in the following information:");
        centerPanel.add(fillIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 124, 634, -1));

        firstNamelb.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        firstNamelb.setText("First Name:");
        centerPanel.add(firstNamelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 200, -1, -1));

        firstName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });
        centerPanel.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 199, 414, 42));

        lastNamelb.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lastNamelb.setText("Last Name:");
        centerPanel.add(lastNamelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 254, -1, 38));

        lastName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        centerPanel.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 257, 414, 38));

        info1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        info1.setForeground(new java.awt.Color(102, 102, 102));
        info1.setText("Your public profile only shows your first name. When you request a booking,");
        centerPanel.add(info1, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 302, -1, -1));
        centerPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        clear.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        centerPanel.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 888, 112, -1));

        signIn.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        signIn.setText("Sign in");
        signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInActionPerformed(evt);
            }
        });
        centerPanel.add(signIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(889, 888, -1, -1));

        info2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        info2.setForeground(new java.awt.Color(102, 102, 102));
        info2.setText("your host will see your first and last name.");
        centerPanel.add(info2, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 328, 516, -1));

        genderlb.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        genderlb.setText("Gender:");
        centerPanel.add(genderlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 381, -1, -1));

        gender.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female" }));
        centerPanel.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 381, 96, 34));

        info3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        info3.setForeground(new java.awt.Color(102, 102, 102));
        info3.setText("We use this data for analysis and never share it with other users.");
        centerPanel.add(info3, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 422, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("Birth Date:");
        centerPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 479, -1, -1));

        month.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        centerPanel.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 477, 72, 39));

        day.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        centerPanel.add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(926, 477, 70, 39));

        year.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971" }));
        centerPanel.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 477, -1, 39));

        emailAddresslb.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        emailAddresslb.setText("Email Address:");
        centerPanel.add(emailAddresslb, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 572, -1, -1));

        emailAddress.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        centerPanel.add(emailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 572, 610, 35));

        phoneNumberlb.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        phoneNumberlb.setText("Phone Number:");
        centerPanel.add(phoneNumberlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 667, -1, -1));

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("We use this data for analysis and never share it with other users.");
        centerPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 523, -1, -1));

        info4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        info4.setForeground(new java.awt.Color(102, 102, 102));
        info4.setText("We use this data for analysis and never share it with other users.");
        centerPanel.add(info4, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 614, -1, -1));

        info5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        info5.setForeground(new java.awt.Color(102, 102, 102));
        info5.setText("We use this data for analysis and never share it with other users.");
        centerPanel.add(info5, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 703, 516, -1));

        phoneNumber.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        centerPanel.add(phoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 661, 610, 35));

        passwordlb.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        passwordlb.setText("Password:");
        centerPanel.add(passwordlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 746, -1, 38));

        passWord.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        centerPanel.add(passWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 749, 610, 38));

        confirmlb.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        confirmlb.setText("Confirm Password:");
        centerPanel.add(confirmlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 818, -1, -1));

        confirmPassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        centerPanel.add(confirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 817, 610, 36));

        confirmInfo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        confirmInfo.setForeground(new java.awt.Color(255, 0, 0));
        centerPanel.add(confirmInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1173, 817, 339, 36));

        passwordinfo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        passwordinfo.setForeground(new java.awt.Color(204, 0, 0));
        centerPanel.add(passwordinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1177, 749, 327, 38));

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(backgroundLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 1537, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(backgroundLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInActionPerformed
        signin(userDB , firstName.getText(), lastName.getText(), gender.getItemAt(gender.getSelectedIndex()), year.getItemAt(year.getSelectedIndex()), month.getItemAt(month.getSelectedIndex()),
            day.getItemAt(day.getSelectedIndex()), emailAddress.getText(), phoneNumber.getText(), passWord.getText());
        String u = String.valueOf(userid);
        addTable("user"+u);
        if (isEmpty(passWord.getText())) {
            passwordinfo.setText("Password cannot be empty!");
        }
        else if(checkconfirmPSW()){
            new Success(u);
        }
        

    }//GEN-LAST:event_signInActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        firstName.setText("");
        lastName.setText("");
        info1.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed
    
    private boolean isEmpty(String s){
        if (s.equals("")) 
            return true;
        else
            return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SignIn signIn = new SignIn();
                signIn.setVisible(true);
                signIn.setLocationRelativeTo(null);
            }
        });
    }
    
    public void signin(UserDB userDB,String firstName, String lastName , String gender, String year ,String month,String day,String email, String phone,String password){
        try {
            ResultSet rs = userDB.statement.executeQuery("select * from userinfo where userid =(select max(userid) from userinfo) ");
           
            while(rs.next()){
                 userid = rs.getInt("userid")+1;
            }
            int date = Integer.valueOf(year+month+day);
            String stateString = "insert into userinfo values("+userid+",'"+firstName+"','"+lastName+"','"+gender+"','"+email+"','"+phone+"','"+password+"','"+date+"')";
            userDB.statement.executeUpdate(stateString);
        } catch (SQLException ex) {
            Logger.getLogger(SignIn.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void addTable(String userid){
        try {
            userDB.statement.executeUpdate("create table user"+ userid+" "
                    +"(userid int,"
                    + "hotelid varchar(50),"
                    + "hotelName varchar(50),"
                    + "orderTime VARCHAR(50),"
                    + "leaveTime VARCHAR(50))");
        } catch (SQLException ex) {
            Logger.getLogger(SignIn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    
    public boolean checkconfirmPSW(){
        if (!passWord.getText().equals(confirmPassword.getText())) {
            confirmInfo.setText("The passswords are not the same!");
            return false;
        }
        else
            return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JButton clear;
    private javax.swing.JLabel confirmInfo;
    private javax.swing.JTextField confirmPassword;
    private javax.swing.JLabel confirmlb;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JTextField emailAddress;
    private javax.swing.JLabel emailAddresslb;
    private javax.swing.JLabel fillIn;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel firstNamelb;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel genderlb;
    private javax.swing.JLabel info1;
    private javax.swing.JLabel info2;
    private javax.swing.JLabel info3;
    private javax.swing.JLabel info4;
    private javax.swing.JLabel info5;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField lastName;
    private javax.swing.JLabel lastNamelb;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField passWord;
    private javax.swing.JLabel passwordinfo;
    private javax.swing.JLabel passwordlb;
    private javax.swing.JTextField phoneNumber;
    private javax.swing.JLabel phoneNumberlb;
    private javax.swing.JButton signIn;
    private javax.swing.JLabel signInlb;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
